# -*- coding: utf-8 -*-
"""1BM23AI093_DEL_LAB09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zi8lXU87Wyg6L1oVCRaDnfDF0hyDVEjU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error ,mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU,Dense,Dropout
import yfinance as yf

def fetch_stock_data(ticker,start_date,end_date):
    data=yf.download(ticker,start=start_date,end=end_date)
    return data
ticker='AAPL'
data=fetch_stock_data(ticker,start_date='2010-01-01',end_date='2023-01-01')
print(data.head())
data=data.sort_values('Date')
data=data[[('Open',ticker)]]
dataset=data.values
training_data_len=int(np.ceil(len(dataset)*0.8))
scaler=MinMaxScaler(feature_range=(0,1))
scaled_data=scaler.fit_transform(dataset)
train_data=scaled_data[0:int(training_data_len),:]
x_train=[]
y_train=[]
for i in range(60,len(train_data)):
  x_train.append(train_data[i-60:i,0])
  y_train.append(train_data[i,0])
x_train,y_train=np.array(x_train),np.array(y_train)
x_train=np.reshape(x_train,(x_train.shape[0],x_train.shape[1],1))
model=Sequential()
model.add(GRU(units=50,return_sequences=True,input_shape=(x_train.shape[1],1)))
model.add(Dropout(0.2))
model.add(GRU(units=50,return_sequences=False))
model.add(Dropout(0.2))
model.add(Dense(units=25))
model.add(Dense(units=1))
model.compile(optimizer='adam',loss='mean_squared_error')
model.fit(x_train,y_train,batch_size=1,epochs=1)
test_data=scaled_data[training_data_len-60:,:]
x_test=[]
y_test=dataset[training_data_len:,:]
for i in range(60,len(test_data)):
  x_test.append(test_data[i-60:i,0])
x_test=np.array(x_test)
x_test=np.reshape(x_test,(x_test.shape[0],x_test.shape[1],1))
predictions=model.predict(x_test)
predictions=scaler.inverse_transform(predictions)

rmse=np.sqrt(mean_squared_error(y_test,predictions))
print(f'Root Mean Squared Error:{rmse:.4f}')
mae=mean_absolute_error(y_test,predictions)
print(f'Mean Absolute Error:{mae:.4f}')
train=data[:training_data_len]
valid=data[training_data_len:]
valid['Predictions']=predictions
plt.figure(figsize=(16,8))
plt.title('Model')
plt.xlabel('Date')
plt.ylabel('open Price USD ($)')
plt.plot(train['Open'])
plt.plot(valid[['Open','Predictions']])
plt.legend(['Train','val','predictions'],loc='lower right')
plt.show()
print(valid)

