# -*- coding: utf-8 -*-
"""1BM23AI093_DEL_LAB07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mmWA_c-rIUC6Y4hkcofvMalFKdYcLwhe
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Flatten,Dense,Dropout
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt

(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train=x_train.astype('float32')/255.0
x_test=x_test.astype('float32')/255.0

x_train=x_train.reshape((x_train.shape[0],28,28,1))
x_test=x_test.reshape((x_test.shape[0],28,28,1))
y_train=to_categorical(y_train,10)
y_test=to_categorical(y_test,10)

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    MaxPooling2D((2,2)),
    Dropout(0.25),
    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D((2,2)),
    Dropout(0.25),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(10, activation='softmax')
])

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
history=model.fit(x_train,y_train,validation_split=0.1,epochs=5,batch_size=128,verbose=2)
test_loss,test_acc=model.evaluate(x_test,y_test,verbose=2)
print(f'Test accuracy:{test_acc:.4f}')

print("="*70)
print("MODEL")
model.summary()

plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train','Validation'],loc='upper left')
plt.subplot(1,2,2)
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train','Validation'],loc='upper left')
plt.show()

import numpy as np
predictions=model.predict(x_test)
predicted_labels=[tf.argmax(tf.convert_to_tensor(prediction)).numpy()
for prediction in predictions]
plt.figure(figsize=(10,4))
num_images=3
for i in range(num_images):
  plt.subplot(1,num_images,i+1)
  plt.imshow(x_test[i].reshape(28,28),cmap='gray')
  plt.title(f"Predicted:{predicted_labels[i]},True:{np.argmax(y_test[i])}")
  plt.axis('off')
plt.show()

